### ISSUE TITLE
Seamlessly integrate state-of-the-art transformer models into robotics stacks (embodied-agents)

### ISSUE THREAD

**Issue by nqyy** [zchoi/Awesome-Embodied-Agent-with-LLMs#10]
I'd like to share our recent open-sourceproject embodied-agents: https://github.com/mbodiai/embodied-agents, which makes it easy to integrate large multi-modal models into existing robot stacks with just a few lines of code. It has many modalities and support large language model, vision language mode, robotic transformers, and CV models in the form of different agents.

I think it will be helpful for lots of people looking for similar tools. It'll be great to add it to the list. Let me know if you have any questions. Thanks!

**Comment by zchoi** [comment]
LGTM

**Comment by nqyy** [comment]
Thanks!
